#ifndef MOTION_CONTROLLER_CONFIG_H_
#define MOTION_CONTROLLER_CONFIG_H_

#include <config/stepper_config.h>

#define MOT_X_MOTION_MAX_SPEED 1200.f
#define MOT_X_MOTION_MAX_ACCEL 400.f
#define MOT_X_MOTION_MAX_JERK 4000.f
// jerk*dt = accel change per tick (dt is around 1/100)

#define MOT_YAW_MOTION_MAX_SPEED 120.f
#define MOT_YAW_MOTION_MAX_ACCEL 100.f
#define MOT_YAW_MOTION_MAX_JERK 200.f

#define MOT_Z_MOTION_MAX_SPEED 460.f
#define MOT_Z_MOTION_MAX_ACCEL 360.f
#define MOT_Z_MOTION_MAX_JERK 8000.f

#define MOT_U_MOTION_MAX_SPEED 2000.f * MOT_U_ROT_PER_STEP / MOT_U_GEAR_RATIO
#define MOT_U_MOTION_MAX_ACCEL 2000.f * MOT_U_ROT_PER_STEP / MOT_U_GEAR_RATIO
#define MOT_U_MOTION_MAX_JERK 2000.f * MOT_U_ROT_PER_STEP / MOT_U_GEAR_RATIO
#endif
