#ifndef MOTION_CONTROLLER_CONFIG_H_
#define MOTION_CONTROLLER_CONFIG_H_

#include <config/stepper_config.h>

// in units (per second ^0 ^1 ^2 or ^3, respectively)
#define MOT_X_MOTION_MIN_SPEED 10.f
#define MOT_X_MOTION_MAX_SPEED 2000.f
#define MOT_X_MOTION_MAX_ACCEL 4000.f
#define MOT_X_MOTION_MAX_JERK 30000.f
#define MOT_X_MOTION_SHORT_DIST 5.f // mm

#define MOT_YAW_MOTION_MIN_SPEED 10.f
#define MOT_YAW_MOTION_MAX_SPEED 800.f
#define MOT_YAW_MOTION_MAX_ACCEL 800.f
#define MOT_YAW_MOTION_MAX_JERK 8000.f
#define MOT_YAW_MOTION_SHORT_DIST 2.f // deg

#define MOT_Z_MOTION_MIN_SPEED 10.f
#define MOT_Z_MOTION_MAX_SPEED 2000.f
#define MOT_Z_MOTION_MAX_ACCEL 5000.f
#define MOT_Z_MOTION_MAX_JERK 12000.f
#define MOT_Z_MOTION_SHORT_DIST 20.f // mm

#define MOT_U_MOTION_MIN_SPEED 10.f
#define MOT_U_MOTION_MAX_SPEED 2000.f
#define MOT_U_MOTION_MAX_ACCEL 2000.f
#define MOT_U_MOTION_MAX_JERK 2000.f
#define MOT_U_MOTION_SHORT_DIST 10.f // mm

#endif
