gigatino_ros:
  ros__parameters:
    local_ip_address: "192.168.1.112"
    remote_ip_address: "192.168.1.111"
    send_port: 8888
    recv_port: 8889
    command_timeout_ms: 15000
    max_send_attempts: 3
