# no need to provide the node name, common param file for all instances
/**:
  ros__parameters:
    static_transforms:
      gripper_z_origin:
        child_frame_id: gripper_z_origin
        parent_frame_id: base_link
        translation: [0.065, -0.060, 0.40692]
        rotation: [0.0, 0.0, 0.0]
      gripper_yaw_origin:
        child_frame_id: gripper_yaw_origin
        parent_frame_id: gripper_z_dyn
        translation: [0.0325, 0.0, 0.405]
        rotation: [0.910, 0.0, 0.0]
      gripper_x_origin:
        child_frame_id: gripper_x_origin
        parent_frame_id: gripper_yaw_dyn
        translation: [0.04025, 0.03955, 0.0905]
        rotation: [0.0, 0.0, 0.0]
      gripper_end_effector:
        child_frame_id: gripper_end_effector
        parent_frame_id: gripper_x_dyn
        translation: [0.029621, -0.0002, -0.027]
        rotation: [0.0, 0.0, 0.0]
      gripper_home_origin:
        child_frame_id: gripper_home_origin
        parent_frame_id: base_link
        translation: [0.0975, -0.060, 0.875]
        rotation: [0.910, 0.0, 0.0]
      gripper_cam:
        child_frame_id: gripper_cam
        parent_frame_id: gripper_yaw_dyn
        translation: [0.0251, 0.060, 0.0875]
        rotation: [0.0, 0.0, 0.0]
      end_effector_home:
        child_frame_id: end_effector_home
        parent_frame_id: base_link
        translation: [0.109, 0.019, 0.875]
        rotation: [0.0, 0.0, 0.0]
